services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=SmartTestDb;User=sa;Password=DbPassword_123456789;TrustServerCertificate=True
      - ApiKey=abc12def
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DbPassword_123456789
    ports:
      - "1433:1433"
